// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/init_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6689427248019125466),
      name: 'InitEntity',
      lastPropertyId: const IdUid(3, 3782080692178737797),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1650217479814353056),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 2060379890497358099),
            name: 'isInitialStartUp',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3782080692178737797),
            name: 'isInitialLogin',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 6689427248019125466),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    InitEntity: EntityDefinition<InitEntity>(
        model: _entities[0],
        toOneRelations: (InitEntity object) => [],
        toManyRelations: (InitEntity object) => {},
        getId: (InitEntity object) => object.id,
        setId: (InitEntity object, int id) {
          if (object.id != id) {
            throw ArgumentError('Field InitEntity.id is read-only '
                '(final or getter-only) and it was declared to be self-assigned. '
                'However, the currently inserted object (.id=${object.id}) '
                "doesn't match the inserted ID (ID $id). "
                'You must assign an ID before calling [box.put()].');
          }
        },
        objectToFB: (InitEntity object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.isInitialStartUp);
          fbb.addInt64(2, object.isInitialLogin);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = InitEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              isInitialStartUp: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              isInitialLogin: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [InitEntity] entity fields to define ObjectBox queries.
class InitEntity_ {
  /// see [InitEntity.id]
  static final id =
      QueryIntegerProperty<InitEntity>(_entities[0].properties[0]);

  /// see [InitEntity.isInitialStartUp]
  static final isInitialStartUp =
      QueryIntegerProperty<InitEntity>(_entities[0].properties[1]);

  /// see [InitEntity.isInitialLogin]
  static final isInitialLogin =
      QueryIntegerProperty<InitEntity>(_entities[0].properties[2]);
}
